**Question-1**

Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
  1. Addition of 2 in all the element
  2. Multiply 3 with all the elements
  3. Divide every element by 2

In [3]:
import numpy as np
a1 = np.array([10,20,30,40])
print(a1)
print(a1+2)
print(a1*3)
print(a1/2)

[10 20 30 40]
[12 22 32 42]
[ 30  60  90 120]
[ 5. 10. 15. 20.]


**Question-2**

Questions on Basic NumPy Array:
1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
2. Find the most frequent value and their indice(s) in the following arrays:
  1. x = np.array([1,2,3,4,5,1,2,1,1,1])
  2. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,])

In [34]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original Array",arr)
arr = arr[::-1]
print("Reversed Array",arr,end='\n\n')

x = np.array([1,2,3,4,5,1,2,1,1,1])
most_freq_x = np.bincount(x).argmax();
most_freq_x_idxs = np.where(x==most_freq_x)[0]
print(most_freq_x)
print(most_freq_x_idxs,end='\n\n')

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,])
most_freq_y = np.bincount(y).argmax();
most_freq_y_idxs = np.where(y==most_freq_x)[0]
print(most_freq_y)
print(most_freq_y_idxs)

Original Array [1 2 3 6 4 5]
Reversed Array [5 4 6 3 2 1]

1
[0 5 7 8 9]

1
[0 1 2]


**Question-3**

For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]),access elements using row and column indices as follows:
  1. Access 1st row, 2nd column
  2. Access 3rd row, 1st column

In [11]:
a2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("1st row, 2nd column:",a2[0,2])
print("3rd row, 1st column:",a2[2,0])

1st row, 2nd column: 30
3rd row, 1st column: 70


**Question-4**

1. Write program to create an 1-D NumPy array named (Your Name) with evenly
spaced 25 numbers from 10 to 100 using linspace().
2. Print the dimensions of the array,shape,total elements,the data type of each element and total number of bytes consumed by the array.
3. Find the transpose of this array using  reshape() attribute.
4. Can we do the same with T attribute?

In [21]:
devansh = np.linspace(10,100,25)
print(devansh,end='\n\n')

print("Dimensions of the array:",devansh.ndim)
print("Shape of the array:",devansh.shape)
print("Total elements in the array:",devansh.size)
print("Data type of each element:",devansh.dtype)
print("Total bytes consumed by the array:",devansh.nbytes,end='\n\n')

# Transpose of the Array
# temporary modification using reshape
print(devansh.reshape(25,1),end='\n\n')

# using T
devansh.T
# we do not get the same results using T...It does not modify the original Shape

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total bytes consumed by the array: 200

[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]



array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

**Question-5**

1. Create a 2-D Array of three rows and four columns, named ucs420 with following values: 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35.
2. Compute the mean,median, max, min, unique elements.
3. Reshape the array to four rows and three columns and name it as
reshaped_ ucs420.
4. Resize the array to two rows and three columns and name it as
resized_ ucs420.

In [31]:
ucs420 = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420,end='\n\n')

print("Mean of ucs420 is:",np.mean(ucs420))
print("Median of ucs420 is:",np.median(ucs420))
print("Max Value in ucs420 is:",np.max(ucs420))
print("Min Value in ucs420 is:",np.min(ucs420))
print("Unique values of ucs420 are:",np.unique(ucs420),end='\n\n')

reshaped_ucs420 = ucs420.reshape(4,3)
print(reshaped_ucs420,end='\n\n')

resized_ucs420 = np.resize(ucs420,(2,3))
print(resized_ucs420,end='\n\n')

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

(3, 4)
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Mean of ucs420 is: 43.333333333333336
Median of ucs420 is: 37.5
Max Value in ucs420 is: 90
Min Value in ucs420 is: 10
Unique values of ucs420 are: [10 15 20 30 35 40 50 60 70 80 90]

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

[[10 20 30]
 [40 50 60]]

